[package]
name = "next-build"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[features]
native-tls = ["next-core/native-tls"]
rustls-tls = ["next-core/rustls-tls"]
custom_allocator = ["turbopack-binding/__turbo_tasks_malloc", "turbopack-binding/__turbo_tasks_malloc_custom_allocator"]

[dependencies]
anyhow = "1.0.47"
next-core = { workspace = true }

turbopack-binding = { workspace = true, features = ["__turbo_tasks", "__turbo_tasks_memory"] }

[build-dependencies]
turbopack-binding = { workspace = true, features = ["__turbo_tasks_build"] }
vergen = { version = "7.3.2", default-features = false, features = [
  "cargo",
  "build",
] }
