[package]
name = "next-dev"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[[bin]]
name = "next-dev"
path = "src/main.rs"
bench = false

[lib]
bench = false

[[bench]]
name = "mod"
harness = false

[features]
# By default, we enable native-tls for reqwest via downstream transitive features.
# This is for the convenience of running daily dev workflows, i.e running
# `cargo xxx` without explicitly specifying features, not that we want to
# promote this as default backend. Actual configuration is done when building next-swc,
# and also turbopack standalone when we have it.
default = ["cli", "custom_allocator", "native-tls"]
cli = ["clap"]
serializable = []
tokio_console = [
  "dep:console-subscriber",
  "tokio/tracing",
  "turbo-tasks/tokio_tracing",
]
profile = []
custom_allocator = ["turbopack-binding/__turbo_tasks_malloc", "turbopack-binding/__turbo_tasks_malloc_custom_allocator"]
native-tls = ["next-core/native-tls"]
rustls-tls = ["next-core/rustls-tls"]
# Internal only. Enabled when building for the Next.js integration test suite.
__internal_nextjs_integration_test = [
  "next-core/__internal_nextjs_integration_test",
]
# enable "HMR" for embedded assets
dynamic_embed_contents = [
  "next-core/dynamic_embed_contents",
  "turbopack-binding/__turbopack_node_dynamic_embed_contents",
  "turbopack-binding/__turbopack_dev_dynamic_embed_contents",
]

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true, features = ["derive", "env"], optional = true }
console-subscriber = { workspace = true, optional = true }
dunce = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
mime = { workspace = true }
next-core = { workspace = true }
owo-colors = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turbopack-binding = { workspace = true, features = [
  "__turbo_tasks_memory",
  "__turbo_tasks_env",
  "__turbo_tasks_fs",
  "__turbopack",
  "__turbopack_core",
  "__turbopack_dev",
  "__turbopack_env",
  "__turbopack_cli_utils",
  "__turbopack_node",
  "__turbopack_dev_server",
]}
turbo-tasks = { workspace = true }
webbrowser = { workspace = true }

[dev-dependencies]
chromiumoxide = { workspace = true, features = [
  "tokio-runtime",
], default-features = false }
criterion = { workspace = true, features = ["async_tokio"] }
once_cell = { workspace = true }
parking_lot = { workspace = true }
portpicker = "0.1.1"
rand = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tungstenite = { workspace = true }
turbopack-binding = { workspace = true, features = [
  "__turbopack_bench",
]}
url = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
nix = "0.26.1"

[build-dependencies]
turbopack-binding = { workspace = true, features = [
  "__turbo_tasks_build"
]}
vergen = { version = "7.3.2", default-features = false, features = [
  "cargo",
  "build",
] }
