# https://github.com/github/issue-labeler#create-workflow

name: Label issues - GH Labeler

on:
  issues:
    types: [opened]

jobs:
  triage:
    if: |
      ${{ github.event.label.name == 'template: bug' }}
    name: Triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Run issue labeler'
        run: node ./.github/actions/issue-labeler/lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
